### ISSUE TITLE
Tally of on behalf of votes is wrong on comments

### ISSUE THREAD

**Issue by joshuakrafchin** [unitedvote/united.vote#57]
Derek represents 58 people, but the system says he only voted on behalf of 1.

![image](https://user-images.githubusercontent.com/23617532/42071065-1821f94a-7b0e-11e8-9fa7-daa44861b8c8.png)

**Comment by alexmingoia** [comment]
This is technically correct. It's very confusing, because the "Derek represents 58 people" count is a *maximum* number of people that Derek might represent on any bill. It's not the number of people directly proxying to Derek (which may only be 1). For this particular bill, he only controlled the vote of one other person. One of the users proxying to Derek inherited Derek's vote, and nobody is proxying to them. Everyone else proxying to Derek voted directly.

Does that make sense?

**Comment by dsernst** [comment]
Related to https://github.com/unitedvote/united.vote/issues/22
